const TipoExp = {
    PRIMITIVO:   "PRIMITIVO",
    ARITMETICO:  "ARITMETICO",
    LOGICO:      "LOGICO",
    RELACIONAL:  "RELACIONAL",
    TERNARIO:    "TERNARIO",
    ACCESOVAR:   "ACCESOVAR",
    FUNCNATIVA:  "FUNCNATIVA",
    ACCESOVEC:   "ACCESOVEC",
    CASTEO:      "CASTEO",
    LLAMADAFUNC: "LLAMADAFUNC",
    RETURN:      "RETURN",
}

module.exports = { TipoExp }